name : Portfolio deployment

on : 
  push: 
    branches : main

jobs: 
  build-deploy: 
    runs-on : ubuntu-latest
    steps: 
    - name : checkout the repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://kdstaticweb --delete
